import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { EmptyState } from '@/components/ui/EmptyState';
import { LoadingState } from '@/components/ui/LoadingState';
import { Notice } from '@/components/ui/Notice';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { PASS_MARK } from '@/constants/config';
import { skillLabel } from '@/constants/skills';
import { getTestQuestions } from '@/constants/skillTestBank';
import { colors, radius, sizes, spacing, type } from '@/constants/theme';
import { useAuth } from '@/hooks/useAuth';
import { markSkillVerified, saveTestAttempt } from '@/services/userService';
import type { SkillTag } from '@/types';
import { errorMessage } from '@/utils/authErrors';

type Result = { score: number; passed: boolean; correct: number };

export default function SkillTestScreen() {
  const { skill } = useLocalSearchParams<{ skill: string }>();
  const { profile, refreshProfile } = useAuth();

  const skillTag = skill as SkillTag;
  const questions = useMemo(() => getTestQuestions(skillTag), [skillTag]);

  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (!profile) return <LoadingState fullScreen label="Loading…" />;

  const alreadyVerified = profile.verifiedSkills.includes(skillTag);
  const answered = Object.keys(answers).length;

  if (questions.length === 0) {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <ScreenHeader title="Skill test" showBack />
        <EmptyState
          icon="help-circle-outline"
          title={`No test for ${skillLabel(skillTag)} yet`}
          message="Tests are written for the most common skills and generated by AI for the rest — AI generation arrives with the Gemini features in Week 7."
          actionLabel="Go back"
          onAction={() => router.back()}
        />
      </SafeAreaView>
    );
  }

  async function onSubmit() {
    setError(null);
    setSubmitting(true);

    const ordered = questions.map((_, index) => answers[index] ?? '');
    const correct = questions.reduce(
      (total, question, index) => (ordered[index] === question.answer ? total + 1 : total),
      0
    );
    const score = Math.round((correct / questions.length) * 100);
    const passed = score >= PASS_MARK;

    try {
      // The attempt is recorded whether it passed or not — a verification claim
      // needs a trail, and a failed attempt is how the pass mark stays meaningful.
      await saveTestAttempt(profile!.uid, skillTag, questions, ordered, score, passed, 'fallback');

      if (passed) {
        await markSkillVerified(profile!.uid, skillTag);
        await refreshProfile();
      }

      setResult({ score, passed, correct });
    } catch (submitError) {
      setError(errorMessage(submitError));
    } finally {
      setSubmitting(false);
    }
  }

  if (result) {
    return (
      <SafeAreaView style={styles.safe} edges={['top']}>
        <ScreenHeader title="Result" showBack />
        <ScrollView contentContainerStyle={styles.content}>
          <View style={styles.resultBlock}>
            <Ionicons
              name={result.passed ? 'checkmark-circle' : 'close-circle-outline'}
              size={sizes.avatarLg}
              color={result.passed ? colors.success : colors.warning}
            />
            <Text style={styles.resultScore}>{result.score}%</Text>
            <Text style={styles.resultTitle}>
              {result.passed
                ? `${skillLabel(skillTag)} is now verified`
                : `Not quite — ${PASS_MARK}% is the pass mark`}
            </Text>
            <Text style={styles.resultMeta}>
              {result.correct} of {questions.length} correct
            </Text>
          </View>

          <Notice
            tone={result.passed ? 'success' : 'info'}
            message={
              result.passed
                ? 'A filled tick now appears next to this skill. It means SkillBridge tested you — separate from any certificate you upload.'
                : 'You can retake the test. Every attempt is recorded, so the badge keeps its meaning.'
            }
          />

          <View style={styles.review}>
            {questions.map((question, index) => {
              const given = answers[index] ?? '';
              const isCorrect = given === question.answer;

              return (
                <Card key={question.q}>
                  <Text style={styles.reviewQuestion}>{question.q}</Text>
                  <Text style={[styles.reviewAnswer, isCorrect ? styles.correct : styles.wrong]}>
                    Your answer: {given || 'not answered'}
                  </Text>
                  {isCorrect ? null : (
                    <Text style={styles.reviewAnswer}>Correct answer: {question.answer}</Text>
                  )}
                </Card>
              );
            })}
          </View>

          <Button label="Done" onPress={() => router.back()} />
        </ScrollView>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safe} edges={['top', 'bottom']}>
      <ScreenHeader
        title={`Verify ${skillLabel(skillTag)}`}
        subtitle={`${questions.length} questions · ${PASS_MARK}% to pass`}
        showBack
      />

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        {error ? <Notice tone="error" message={error} /> : null}

        {alreadyVerified ? (
          <Notice
            tone="info"
            message="You have already verified this skill. Retaking the test cannot remove the badge."
          />
        ) : null}

        {questions.map((question, index) => (
          <View key={question.q} style={styles.question}>
            <Text style={styles.questionNumber}>
              Question {index + 1} of {questions.length}
            </Text>
            <Text style={styles.questionText}>{question.q}</Text>

            <View style={styles.options}>
              {(question.options ?? []).map((option) => (
                <Option
                  key={option}
                  label={option}
                  selected={answers[index] === option}
                  onPress={() => setAnswers((previous) => ({ ...previous, [index]: option }))}
                />
              ))}
            </View>
          </View>
        ))}
      </ScrollView>

      <View style={styles.submitBar}>
        <Text style={styles.progress}>
          {answered} of {questions.length} answered
        </Text>
        <Button
          label="Submit answers"
          onPress={onSubmit}
          loading={submitting}
          disabled={answered < questions.length}
        />
      </View>
    </SafeAreaView>
  );
}

/**
 * A full-width row rather than a chip: an answer that is truncated to one line is
 * an answer the candidate cannot judge, which would make the score meaningless.
 */
function Option({
  label,
  selected,
  onPress,
}: {
  label: string;
  selected: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      onPress={onPress}
      accessibilityRole="radio"
      accessibilityState={{ selected }}
      accessibilityLabel={label}
      style={({ pressed }) => [
        styles.option,
        selected && styles.optionSelected,
        pressed && !selected && styles.optionPressed,
      ]}>
      <Ionicons
        name={selected ? 'radio-button-on' : 'radio-button-off'}
        size={sizes.iconMd}
        color={selected ? colors.accent : colors.inkFaint}
      />
      <Text style={[styles.optionLabel, selected && styles.optionLabelSelected]}>{label}</Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  content: {
    gap: spacing.xl,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
  },
  question: {
    gap: spacing.sm,
  },
  questionNumber: {
    ...type.caption,
    color: colors.inkMuted,
  },
  questionText: {
    ...type.h2,
    color: colors.ink,
  },
  options: {
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    minHeight: sizes.control,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: StyleSheet.hairlineWidth * 2,
    borderColor: colors.border,
  },
  optionSelected: {
    backgroundColor: colors.accentSurface,
    borderColor: colors.accent,
  },
  optionPressed: {
    borderColor: colors.inkFaint,
  },
  optionLabel: {
    ...type.body,
    color: colors.ink,
    flex: 1,
  },
  optionLabelSelected: {
    ...type.bodyStrong,
    color: colors.ink,
  },
  submitBar: {
    gap: spacing.sm,
    padding: spacing.lg,
    backgroundColor: colors.surface,
    borderTopWidth: StyleSheet.hairlineWidth * 2,
    borderTopColor: colors.border,
  },
  progress: {
    ...type.caption,
    color: colors.inkMuted,
    textAlign: 'center',
  },
  resultBlock: {
    alignItems: 'center',
    gap: spacing.sm,
  },
  resultScore: {
    ...type.display,
    color: colors.ink,
  },
  resultTitle: {
    ...type.h2,
    color: colors.ink,
    textAlign: 'center',
  },
  resultMeta: {
    ...type.caption,
    color: colors.inkMuted,
  },
  review: {
    gap: spacing.md,
  },
  reviewQuestion: {
    ...type.bodyStrong,
    color: colors.ink,
    marginBottom: spacing.xs,
  },
  reviewAnswer: {
    ...type.caption,
    color: colors.inkMuted,
  },
  correct: {
    color: colors.success,
  },
  wrong: {
    color: colors.danger,
  },
});
