import type { QuizConcept } from './types';

/** Fifteen beginner-friendly concepts for every Academic skill. */
export const ACADEMIC_QUIZ_CONCEPTS = {
  mathematics: [
    ['Integer', 'A whole number that may be positive, negative, or zero'],
    ['Fraction', 'A number representing part of a whole as a numerator over a denominator'],
    ['Percentage', 'A ratio expressed as a number out of one hundred'],
    ['Variable', 'A symbol used to represent a value that may change'],
    ['Equation', 'A statement that two mathematical expressions are equal'],
    ['Coefficient', 'A number multiplying a variable in an expression'],
    ['Exponent', 'A number indicating how many times a base is multiplied by itself'],
    ['Square root', 'A value that produces the original number when multiplied by itself'],
    ['Prime number', 'A whole number greater than one with exactly two positive factors'],
    ['Factor', 'A whole number that divides another number without a remainder'],
    ['Mean', 'The sum of values divided by the number of values'],
    ['Median', 'The middle value after data is arranged in order'],
    ['Probability', 'A number from zero to one measuring how likely an event is'],
    ['Perimeter', 'The total distance around a two-dimensional shape'],
    ['Area', 'The amount of two-dimensional space inside a shape'],
  ],
  physics: [
    ['Distance', 'The total length of the path an object travels'],
    ['Displacement', 'The directed change from starting position to ending position'],
    ['Speed', 'Distance traveled per unit of time'],
    ['Velocity', 'Speed that also includes a direction'],
    ['Acceleration', 'The rate at which velocity changes'],
    ['Force', 'A push or pull that can change motion'],
    ['Mass', 'A measure of the amount of matter in an object'],
    ['Weight', 'The gravitational force acting on an object'],
    ['Newton first law', 'An object keeps its motion unless a net force acts'],
    ['Newton second law', 'Net force equals mass multiplied by acceleration'],
    ['Work', 'Energy transferred when force moves an object through a distance'],
    ['Power', 'The rate at which work is done or energy is transferred'],
    ['Kinetic energy', 'Energy an object has because of its motion'],
    ['Potential energy', 'Stored energy due to position or configuration'],
    ['Electric current', 'The rate of flow of electric charge'],
  ],
  accounting: [
    ['Asset', 'A resource controlled by a business that provides future benefit'],
    ['Liability', 'A present obligation a business must settle'],
    ['Equity', 'The owner residual interest after liabilities are subtracted from assets'],
    ['Revenue', 'Income earned from ordinary business activities'],
    ['Expense', 'A cost consumed while earning revenue'],
    ['Accounting equation', 'The relationship Assets = Liabilities + Equity'],
    ['Debit', 'An entry on the left side of an account'],
    ['Credit', 'An entry on the right side of an account'],
    ['Journal entry', 'A dated record of a transaction using debits and credits'],
    ['Ledger', 'A collection of accounts containing transaction activity'],
    ['Trial balance', 'A list used to check whether total debits equal total credits'],
    ['Income statement', 'A report of revenue, expenses, and profit over a period'],
    ['Balance sheet', 'A report of assets, liabilities, and equity on a date'],
    ['Cash flow statement', 'A report explaining cash received and paid during a period'],
    ['Depreciation', 'Allocating the cost of a long-term asset across its useful life'],
  ],
  'research-writing': [
    ['Research question', 'A focused question that a study aims to answer'],
    ['Thesis statement', 'A concise claim expressing the central argument'],
    ['Literature review', 'A critical synthesis of existing work on a topic'],
    ['Primary source', 'Original evidence or a first-hand account'],
    ['Secondary source', 'Analysis or interpretation of original evidence'],
    ['Peer review', 'Evaluation of scholarly work by experts in the field'],
    ['Citation', 'A reference that identifies the source of an idea or quotation'],
    ['Paraphrase', 'Restating a source idea accurately in new wording'],
    ['Plagiarism', 'Presenting someone else’s work or ideas without proper credit'],
    ['Abstract', 'A brief summary of a research paper and its findings'],
    ['Methodology', 'The approach and procedures used to conduct a study'],
    ['Evidence', 'Information used to support or evaluate a claim'],
    ['Argument', 'A claim supported by reasons and evidence'],
    ['Conclusion', 'The section that answers the question and explains significance'],
    ['Reference list', 'The full publication details of sources cited in a paper'],
  ],
} as const satisfies Record<string, readonly QuizConcept[]>;
