import type { QuizConcept } from './types';

/** Fifteen beginner-friendly concepts for every Business skill. */
export const BUSINESS_QUIZ_CONCEPTS = {
  'public-speaking': [
    ['Audience analysis', 'Learning what listeners know, need, and expect'],
    ['Thesis statement', 'One sentence expressing the central message of a speech'],
    ['Opening hook', 'An introduction device that gains audience attention'],
    ['Signpost', 'A phrase that tells listeners where the speech is going'],
    ['Main point', 'A major idea that directly supports the central message'],
    ['Supporting evidence', 'Examples, facts, or testimony that strengthen a claim'],
    ['Vocal pace', 'The speed at which a speaker talks'],
    ['Vocal variety', 'Changes in pitch, pace, and volume that maintain interest'],
    ['Pause', 'A deliberate silence used for emphasis or clarity'],
    ['Eye contact', 'Looking toward audience members to build connection'],
    ['Open posture', 'A relaxed, uncrossed body position facing the audience'],
    ['Visual aid', 'A supporting image, chart, object, or slide'],
    ['Rehearsal', 'Practicing a speech before delivering it'],
    ['Call to action', 'A clear request for the audience to do something'],
    ['Conclusion', 'The final section that reinforces and closes the message'],
  ],
  'digital-marketing': [
    ['Target audience', 'The specific group a campaign aims to reach'],
    ['Customer persona', 'A research-based profile of an ideal customer type'],
    ['SEO', 'Improving content so search engines can find and rank it'],
    ['Keyword', 'A word or phrase people enter into a search engine'],
    ['Content marketing', 'Creating useful material to attract and retain an audience'],
    ['Email marketing', 'Using permission-based email to communicate with customers'],
    ['Social media marketing', 'Using social platforms to reach and engage an audience'],
    ['Call to action', 'Text or a control prompting the next desired step'],
    ['Conversion', 'A completed action that supports a campaign goal'],
    ['Conversion rate', 'The percentage of visitors who complete the desired action'],
    ['Impression', 'One display of an advertisement or piece of content'],
    ['Click-through rate', 'The percentage of impressions that produce a click'],
    ['Organic reach', 'Unpaid exposure received by content'],
    ['Paid search', 'Advertisements displayed in search results for selected queries'],
    ['A/B test', 'Comparing two variants to see which performs better'],
  ],
  entrepreneurship: [
    ['Problem statement', 'A clear description of the customer difficulty to solve'],
    ['Value proposition', 'The main benefit explaining why customers should choose an offer'],
    ['Target market', 'The group of customers a business intends to serve'],
    ['Business model', 'How an organization creates, delivers, and captures value'],
    ['Revenue stream', 'A particular way a business earns money'],
    ['Cost structure', 'The major expenses required to operate a business'],
    ['Minimum viable product', 'The smallest product used to test important assumptions'],
    ['Customer discovery', 'Interviewing and observing potential customers to test needs'],
    ['Market research', 'Collecting information about customers, competitors, and demand'],
    ['Competitive advantage', 'A valuable strength that rivals cannot easily copy'],
    ['Prototype', 'An early model used to learn before full production'],
    ['Bootstrapping', 'Building a venture mainly with founder resources and revenue'],
    ['Break-even point', 'The sales level at which revenue equals total cost'],
    ['Pitch', 'A concise presentation intended to gain support or investment'],
    ['Pivot', 'A significant strategy change based on evidence and learning'],
  ],
  excel: [
    ['Cell', 'The box at the intersection of a spreadsheet row and column'],
    ['Cell reference', 'An address such as B3 identifying a cell'],
    ['Formula', 'An expression beginning with an equals sign that calculates a value'],
    ['Relative reference', 'A cell reference that changes when copied'],
    ['Absolute reference', 'A dollar-sign reference that stays fixed when copied'],
    ['SUM', 'A function that adds numeric values'],
    ['AVERAGE', 'A function that calculates the arithmetic mean'],
    ['IF', 'A function that returns different values based on a condition'],
    ['COUNT', 'A function that counts cells containing numbers'],
    ['Sort', 'Reordering rows according to one or more columns'],
    ['Filter', 'Temporarily showing only rows that meet selected criteria'],
    ['Table', 'A structured data range with headers and built-in controls'],
    ['Chart', 'A visual representation of worksheet data'],
    ['PivotTable', 'An interactive summary that groups and aggregates data'],
    ['Conditional formatting', 'Automatic cell formatting based on rules'],
  ],
  'business-analysis': [
    ['Stakeholder', 'A person or group affected by or influencing an initiative'],
    ['Business need', 'A problem or opportunity that justifies change'],
    ['Requirement', 'A documented capability or condition that must be met'],
    ['Functional requirement', 'A description of behavior a solution must provide'],
    ['Non-functional requirement', 'A quality constraint such as speed, security, or usability'],
    ['Elicitation', 'Drawing out information from stakeholders and other sources'],
    ['User story', 'A short requirement written from a user perspective'],
    ['Acceptance criteria', 'Testable conditions that define when work is acceptable'],
    ['Process map', 'A visual sequence of activities, decisions, and handoffs'],
    ['As-is process', 'A description of how work happens currently'],
    ['To-be process', 'A description of the desired future way of working'],
    ['Gap analysis', 'Comparing current and desired states to identify differences'],
    ['Scope', 'The boundaries of what an initiative includes and excludes'],
    ['Traceability', 'Linking requirements to their sources, delivery, and tests'],
    ['Root cause analysis', 'Finding the underlying reason a problem occurs'],
  ],
  'project-management': [
    ['Project', 'Temporary work undertaken to create a unique result'],
    ['Scope', 'The defined work and outcomes included in a project'],
    ['Deliverable', 'A verifiable output produced by project work'],
    ['Milestone', 'A significant checkpoint with no duration'],
    ['Task', 'A specific piece of work with an expected result'],
    ['Dependency', 'A relationship where one activity relies on another'],
    ['Stakeholder', 'A person or group interested in or affected by the project'],
    ['Risk', 'An uncertain event that could affect objectives'],
    ['Issue', 'A problem that is already happening and needs action'],
    ['Schedule', 'The planned timing and sequence of project activities'],
    ['Budget', 'The approved estimate of project costs'],
    ['Resource', 'A person, tool, material, or funding used by a project'],
    ['Gantt chart', 'A timeline view showing tasks, durations, and dependencies'],
    ['Change control', 'A process for evaluating and approving scope changes'],
    ['Retrospective', 'A meeting to identify lessons and improve future work'],
  ],
} as const satisfies Record<string, readonly QuizConcept[]>;
