import type { QuizConcept } from './types';

/** Fifteen beginner-friendly concepts for every Design skill. */
export const DESIGN_QUIZ_CONCEPTS = {
  figma: [
    ['Frame', 'A container representing a screen or design region'],
    ['Component', 'A reusable source element shared by multiple instances'],
    ['Instance', 'A linked copy of a component'],
    ['Auto layout', 'A feature that arranges and resizes children automatically'],
    ['Constraint', 'A rule controlling how a layer responds when its frame resizes'],
    ['Variant', 'One configurable version within a component set'],
    ['Prototype connection', 'A link describing navigation or interaction between frames'],
    ['Style', 'A reusable definition for properties such as color or text'],
    ['Variable', 'A reusable value that can change by mode or context'],
    ['Vector', 'A shape defined by mathematical paths and points'],
    ['Mask', 'A shape that controls which parts of other layers are visible'],
    ['Group', 'Several layers collected for easier selection and movement'],
    ['Section', 'A labeled area used to organize related frames on the canvas'],
    ['Comment', 'Feedback attached to a location in a shared design'],
    ['Export', 'Creating an output file such as PNG, SVG, or PDF'],
  ],
  photoshop: [
    ['Layer', 'An independently editable level in an image document'],
    ['Layer mask', 'A reversible way to hide or reveal parts of a layer'],
    ['Adjustment layer', 'A non-destructive layer that changes color or tone'],
    ['Selection', 'A marked area that limits which pixels an edit affects'],
    ['Crop tool', 'A tool used to trim or straighten the canvas'],
    ['Brush tool', 'A tool that paints strokes with a chosen tip and color'],
    ['Clone Stamp', 'A tool that copies pixels from one area to another'],
    ['Healing Brush', 'A tool that blends copied texture with the destination'],
    ['Smart Object', 'A layer that preserves original content for reversible transforms'],
    ['Blend mode', 'A rule controlling how a layer combines with layers below'],
    ['Opacity', 'The degree to which a layer is transparent'],
    ['Resolution', 'The pixel density commonly measured in pixels per inch'],
    ['PSD', 'The native format that preserves Photoshop layers and edits'],
    ['RGB', 'A color mode based on red, green, and blue light'],
    ['CMYK', 'A color mode based on inks commonly used for printing'],
  ],
  illustrator: [
    ['Vector graphic', 'Artwork built from scalable mathematical paths'],
    ['Anchor point', 'A point that defines the position or curve of a path'],
    ['Bezier handle', 'A control used to shape the curve leaving an anchor point'],
    ['Pen tool', 'A tool used to draw precise straight and curved paths'],
    ['Fill', 'The color or pattern inside a closed shape'],
    ['Stroke', 'The visible outline applied to a path'],
    ['Artboard', 'A printable or exportable canvas within a document'],
    ['Pathfinder', 'Tools that combine, subtract, or intersect shapes'],
    ['Clipping mask', 'A shape that limits the visible area of other artwork'],
    ['Group', 'Multiple objects treated as one selection'],
    ['Layers panel', 'The panel used to organize and reorder artwork'],
    ['Type on a Path', 'Text that follows the shape of a vector path'],
    ['Gradient', 'A smooth transition between two or more colors'],
    ['Expand', 'Converting an appearance or object into editable vector shapes'],
    ['SVG', 'A web-friendly file format for scalable vector graphics'],
  ],
  'ui-ux': [
    ['User interface', 'The visual controls and surfaces through which a person interacts'],
    ['User experience', 'The overall quality of a person interaction with a product'],
    ['User research', 'Studying users, goals, and behavior to guide decisions'],
    ['Persona', 'A research-based representation of a target user group'],
    ['User journey', 'A sequence of steps and experiences toward a user goal'],
    ['Information architecture', 'The organization and labeling of content and features'],
    ['Wireframe', 'A low-detail layout showing structure and hierarchy'],
    ['Prototype', 'An interactive model used to explore or test a design'],
    ['Usability test', 'Observing representative users attempt realistic tasks'],
    ['Accessibility', 'Designing so people with varied abilities can use the product'],
    ['Affordance', 'A cue suggesting how an element can be used'],
    ['Visual hierarchy', 'Using size, contrast, and position to show importance'],
    ['Consistency', 'Using familiar patterns and behavior throughout a product'],
    ['Feedback', 'A visible or audible response showing the result of an action'],
    ['Design system', 'Reusable components and standards for consistent products'],
  ],
  'video-editing': [
    ['Timeline', 'The workspace where clips are arranged over time'],
    ['Clip', 'A piece of video, audio, or image media in an edit'],
    ['Cut', 'An immediate transition from one shot to another'],
    ['Transition', 'An effect connecting the end of one clip to the next'],
    ['Frame rate', 'The number of video frames displayed each second'],
    ['Resolution', 'The pixel dimensions of each video frame'],
    ['Aspect ratio', 'The proportional relationship between frame width and height'],
    ['B-roll', 'Supporting footage used over the main narrative or interview'],
    ['Keyframe', 'A point that stores a property value for animation over time'],
    ['Color correction', 'Adjusting footage to make color and exposure accurate'],
    ['Color grading', 'Giving corrected footage a deliberate visual style'],
    ['Audio level', 'The measured loudness of an audio signal'],
    ['Codec', 'A method used to encode and decode media data'],
    ['Container format', 'A file wrapper that holds video, audio, and metadata'],
    ['Render', 'Processing an edit into frames or an output file'],
  ],
} as const satisfies Record<string, readonly QuizConcept[]>;
