import type { QuizConcept } from './types';

/** Fifteen beginner-friendly concepts for every Programming skill. */
export const PROGRAMMING_QUIZ_CONCEPTS = {
  python: [
    ['List', 'An ordered, mutable collection written with square brackets'],
    ['Tuple', 'An ordered collection that cannot be changed after creation'],
    ['Dictionary', 'A collection that stores values under unique keys'],
    ['Set', 'An unordered collection that keeps only unique values'],
    ['def', 'The keyword used to define a function'],
    ['return', 'The statement that sends a value back from a function'],
    ['for loop', 'A loop commonly used to visit each item in an iterable'],
    ['while loop', 'A loop that repeats while its condition remains true'],
    ['if statement', 'A construct that runs code only when a condition is true'],
    ['import', 'The statement used to bring a module into a program'],
    ['len()', 'A built-in function that returns the number of items'],
    ['append()', 'A list method that adds one item to the end'],
    ['Exception', 'An error event that can be handled with try and except'],
    ['Class', 'A blueprint used to create objects'],
    ['Indentation', 'Whitespace that defines code blocks in Python'],
  ],
  javascript: [
    ['const', 'A declaration for a binding that cannot be reassigned'],
    ['let', 'A block-scoped variable declaration that can be reassigned'],
    ['Array', 'An ordered collection written with square brackets'],
    ['Object', 'A collection of key-value properties'],
    ['Function', 'A reusable block of code that can receive arguments'],
    ['Arrow function', 'A compact function syntax that uses an arrow symbol'],
    ['Strict equality', 'A comparison with three equals signs that also checks type'],
    ['map()', 'An array method that transforms every item into a new array'],
    ['filter()', 'An array method that keeps items matching a condition'],
    ['Promise', 'An object representing a future success or failure value'],
    ['async/await', 'Syntax for writing asynchronous code in a sequential style'],
    ['DOM', 'The object model JavaScript uses to read and change a web page'],
    ['Event listener', 'A callback registered to react to an event such as a click'],
    ['JSON', 'A text format commonly used to exchange structured data'],
    ['Template literal', 'A backtick string that can embed expressions'],
  ],
  react: [
    ['Component', 'A reusable unit that returns part of the user interface'],
    ['Props', 'Read-only values passed from a parent component to a child'],
    ['State', 'Component data whose changes can trigger a new render'],
    ['useState', 'A hook that adds a state value to a function component'],
    ['useEffect', 'A hook used to synchronize with systems outside rendering'],
    ['key', 'A stable value React uses to identify items in a rendered list'],
    ['Controlled input', 'An input whose value is managed by React state'],
    ['JSX', 'Syntax that lets markup-like elements appear in JavaScript'],
    ['Fragment', 'A wrapper that groups elements without adding a DOM node'],
    ['Context', 'A way to share a value through a component tree without repeated props'],
    ['useMemo', 'A hook that caches a calculated value between renders'],
    ['useRef', 'A hook that keeps a mutable value without causing renders'],
    ['Conditional rendering', 'Displaying different UI according to a condition'],
    ['Lifting state up', 'Moving shared state to the nearest common parent'],
    ['Virtual DOM', 'React representation used to plan efficient UI updates'],
  ],
  java: [
    ['JVM', 'The virtual machine that executes compiled Java bytecode'],
    ['JDK', 'The development kit containing tools to build Java programs'],
    ['Class', 'A blueprint that defines fields and methods for objects'],
    ['Object', 'An instance created from a class'],
    ['Inheritance', 'A mechanism through which one class reuses another class behavior'],
    ['Interface', 'A contract listing behavior that implementing classes provide'],
    ['Method', 'A named block of behavior defined inside a class'],
    ['Constructor', 'A special member used when a new object is created'],
    ['public', 'An access modifier that allows use from any class'],
    ['private', 'An access modifier that limits use to the declaring class'],
    ['static', 'A modifier that associates a member with the class itself'],
    ['Exception', 'An object representing an error or unusual condition'],
    ['ArrayList', 'A resizable ordered collection from the Java library'],
    ['Package', 'A namespace used to organize related Java classes'],
    ['Garbage collection', 'Automatic recovery of memory from unreachable objects'],
  ],
  sql: [
    ['SELECT', 'The statement used to read columns and rows from a table'],
    ['WHERE', 'A clause that filters individual rows before grouping'],
    ['ORDER BY', 'A clause that sorts query results by one or more columns'],
    ['GROUP BY', 'A clause that combines rows sharing the same values'],
    ['HAVING', 'A clause that filters results after groups are formed'],
    ['INNER JOIN', 'A join that returns only rows matching in both tables'],
    ['LEFT JOIN', 'A join that keeps every left-table row and any matches'],
    ['Primary key', 'A column or set of columns that uniquely identifies a row'],
    ['Foreign key', 'A value that refers to a key in another table'],
    ['INSERT', 'The statement used to add new rows'],
    ['UPDATE', 'The statement used to change existing rows'],
    ['DELETE', 'The statement used to remove rows'],
    ['COUNT()', 'An aggregate function that counts rows or non-null values'],
    ['NULL', 'A marker representing a missing or unknown value'],
    ['Index', 'A data structure that can speed up table lookups'],
  ],
  'html-css': [
    ['Semantic HTML', 'Elements whose names describe the meaning of their content'],
    ['Heading element', 'An h1 through h6 element that defines a section heading'],
    ['Anchor element', 'The HTML element used to create a hyperlink'],
    ['Form', 'An HTML section that collects and submits user input'],
    ['Label', 'Text programmatically associated with a form control'],
    ['alt attribute', 'Text that describes an image when it cannot be seen'],
    ['CSS selector', 'A pattern that chooses which elements a style rule affects'],
    ['Class selector', 'A reusable CSS selector written with a leading dot'],
    ['ID selector', 'A CSS selector written with a leading hash symbol'],
    ['Box model', 'The content, padding, border, and margin around an element'],
    ['Flexbox', 'A one-dimensional CSS layout system for rows or columns'],
    ['CSS Grid', 'A two-dimensional CSS layout system for rows and columns'],
    ['Media query', 'A rule that applies styles according to device conditions'],
    ['Cascade', 'The process CSS uses to combine competing style declarations'],
    ['Specificity', 'The selector-weight calculation used to resolve style conflicts'],
  ],
  git: [
    ['Repository', 'A project directory whose history Git tracks'],
    ['Commit', 'A saved snapshot of staged project changes'],
    ['Staging area', 'The place where changes are prepared for the next commit'],
    ['clone', 'The command that creates a local copy of a remote repository'],
    ['pull', 'The command that fetches and integrates remote changes'],
    ['push', 'The command that sends local commits to a remote repository'],
    ['Branch', 'A movable line of development with its own commit history'],
    ['merge', 'The operation that combines changes from different branches'],
    ['switch', 'A command used to move to another branch'],
    ['status', 'A command that shows changed, staged, and untracked files'],
    ['diff', 'A command that displays line-by-line changes'],
    ['.gitignore', 'A file listing untracked paths Git should normally ignore'],
    ['Remote', 'A named reference to a repository stored elsewhere'],
    ['Merge conflict', 'A change Git cannot combine without human input'],
    ['revert', 'A command that creates a commit undoing an earlier commit'],
  ],
  linux: [
    ['pwd', 'A command that prints the current working directory'],
    ['ls', 'A command that lists directory contents'],
    ['cd', 'A command that changes the current directory'],
    ['mkdir', 'A command that creates a directory'],
    ['cp', 'A command that copies files or directories'],
    ['mv', 'A command that moves or renames a path'],
    ['rm', 'A command that removes paths'],
    ['cat', 'A command that prints or combines file contents'],
    ['grep', 'A command that finds lines matching a text pattern'],
    ['chmod', 'A command that changes file permissions'],
    ['sudo', 'A tool that runs an allowed command with elevated privileges'],
    ['Pipe', 'An operator that sends one command output to another command'],
    ['Redirection', 'Sending command input or output to a file'],
    ['Process', 'A running instance of a program'],
    ['Environment variable', 'A named value available to a process and its children'],
  ],
  'data-structures-algorithms': [
    ['Array', 'A sequence whose items are commonly accessed by numeric index'],
    ['Linked list', 'Nodes connected by references to the next or previous node'],
    ['Stack', 'A last-in, first-out collection'],
    ['Queue', 'A first-in, first-out collection'],
    ['Hash table', 'A structure that maps keys to storage positions using a hash'],
    ['Tree', 'A hierarchical structure made of parent and child nodes'],
    ['Binary search tree', 'A tree where smaller keys are left and larger keys are right'],
    ['Graph', 'Vertices connected by edges'],
    ['Recursion', 'A technique where a function calls itself on a smaller problem'],
    ['Binary search', 'A search that repeatedly halves a sorted search range'],
    ['Linear search', 'A search that checks items one by one'],
    ['Sorting algorithm', 'A procedure that places values into a chosen order'],
    ['Big O notation', 'A way to describe how resource use grows with input size'],
    ['Breadth-first search', 'A traversal that explores neighbors level by level'],
    ['Depth-first search', 'A traversal that follows a path deeply before backtracking'],
  ],
  'rest-apis': [
    ['REST', 'An architectural style centered on resources and standard web methods'],
    ['Endpoint', 'A specific API address where a resource can be accessed'],
    ['GET', 'The HTTP method normally used to retrieve data'],
    ['POST', 'The HTTP method commonly used to create a resource'],
    ['PUT', 'The HTTP method commonly used to replace a full resource'],
    ['PATCH', 'The HTTP method commonly used to update part of a resource'],
    ['DELETE', 'The HTTP method used to remove a resource'],
    ['200 OK', 'A status code indicating a successful request'],
    ['201 Created', 'A status code indicating a resource was created'],
    ['400 Bad Request', 'A status code indicating invalid client input'],
    ['401 Unauthorized', 'A status code indicating valid authentication is required'],
    ['404 Not Found', 'A status code indicating the resource was not found'],
    ['Idempotent operation', 'An operation with the same effect when repeated'],
    ['HTTP header', 'Request or response metadata such as content type'],
    ['JSON', 'A common text representation for API request and response data'],
  ],
  'system-design': [
    ['Scalability', 'The ability of a system to handle increasing work'],
    ['Availability', 'The proportion of time a system can serve requests'],
    ['Reliability', 'The ability to behave correctly and consistently over time'],
    ['Latency', 'The time required to complete one operation or request'],
    ['Throughput', 'The amount of work completed in a period of time'],
    ['Load balancer', 'A component that distributes traffic among servers'],
    ['Cache', 'Fast storage that keeps frequently used data closer to users'],
    ['Replication', 'Keeping copies of data on multiple machines'],
    ['Sharding', 'Splitting a dataset across multiple independent stores'],
    ['Message queue', 'A buffer that lets producers and consumers work independently'],
    ['CDN', 'A distributed network that serves content near users'],
    ['Stateless service', 'A service that keeps no client session between requests'],
    ['Horizontal scaling', 'Adding more machines to increase capacity'],
    ['Vertical scaling', 'Adding resources to an existing machine'],
    ['Single point of failure', 'One component whose failure can stop the whole system'],
  ],
  'cloud-computing': [
    ['IaaS', 'Cloud-provided computing, storage, and networking infrastructure'],
    ['PaaS', 'A managed platform for deploying applications without managing servers'],
    ['SaaS', 'Complete software delivered to users over a network'],
    ['Region', 'A geographic area containing cloud data centers'],
    ['Availability zone', 'An isolated data-center location within a region'],
    ['Virtual machine', 'A software-defined computer running its own operating system'],
    ['Object storage', 'Storage that keeps files as objects addressed by keys'],
    ['Auto scaling', 'Automatically changing resource count to match demand'],
    ['Serverless computing', 'Running code while the provider manages server capacity'],
    ['Cloud load balancer', 'A managed service that distributes incoming traffic'],
    ['IAM', 'Policies and identities controlling access to cloud resources'],
    ['Public cloud', 'Provider-owned infrastructure shared securely by customers'],
    ['Elasticity', 'Rapidly expanding or shrinking resources with demand'],
    ['Backup', 'A separate data copy used for recovery'],
    ['Monitoring', 'Collecting metrics and logs to understand system health'],
  ],
  networking: [
    ['IP address', 'A logical address used to identify a device on a network'],
    ['MAC address', 'A link-layer identifier assigned to a network interface'],
    ['DNS', 'The system that translates domain names into IP addresses'],
    ['DHCP', 'A protocol that automatically supplies network configuration'],
    ['Router', 'A device that forwards packets between different networks'],
    ['Switch', 'A device that connects devices within a local network'],
    ['TCP', 'A reliable, connection-oriented transport protocol'],
    ['UDP', 'A connectionless transport protocol with low overhead'],
    ['HTTP', 'An application protocol used to transfer web resources'],
    ['HTTPS', 'HTTP protected by transport encryption and authentication'],
    ['Port', 'A number identifying a network service on a device'],
    ['Subnet', 'A smaller logical division of an IP network'],
    ['Default gateway', 'The router used to reach destinations outside a local network'],
    ['Packet', 'A formatted unit of data sent across a network'],
    ['Firewall', 'A control that permits or blocks network traffic by rules'],
  ],
  cybersecurity: [
    ['Confidentiality', 'Keeping information hidden from unauthorized people'],
    ['Integrity', 'Protecting information from unauthorized changes'],
    ['Availability', 'Keeping systems and information accessible when needed'],
    ['Authentication', 'Checking that an identity claim is genuine'],
    ['Authorization', 'Deciding what an authenticated identity may do'],
    ['Multi-factor authentication', 'Using two or more different proof types to sign in'],
    ['Phishing', 'A deceptive message intended to steal information or access'],
    ['Malware', 'Software intentionally designed to cause harm'],
    ['Ransomware', 'Malware that blocks data access and demands payment'],
    ['Vulnerability', 'A weakness that could be exploited'],
    ['Security patch', 'An update that fixes a known security weakness'],
    ['Encryption', 'Reversibly transforming data so a key is needed to read it'],
    ['Hashing', 'One-way transformation of data into a fixed-size value'],
    ['Least privilege', 'Giving an identity only the access required for its task'],
    ['Social engineering', 'Manipulating people into weakening security'],
  ],
  'docker-devops': [
    ['Container', 'An isolated process packaged with its application dependencies'],
    ['Image', 'An immutable template used to start containers'],
    ['Dockerfile', 'A text file containing instructions to build an image'],
    ['Registry', 'A service that stores and distributes container images'],
    ['Volume', 'Persistent storage mounted into a container'],
    ['Port mapping', 'Connecting a host port to a container port'],
    ['Docker Compose', 'A tool for defining and running related containers'],
    ['docker build', 'The command that creates an image from build instructions'],
    ['docker run', 'The command that creates and starts a container'],
    ['Continuous integration', 'Automatically building and testing each code change'],
    ['Continuous delivery', 'Keeping validated changes ready for deployment'],
    ['Pipeline', 'An automated sequence of build, test, and delivery steps'],
    ['Environment variable', 'External configuration supplied as a named value'],
    ['Orchestration', 'Automated deployment and coordination of many containers'],
    ['Immutable infrastructure', 'Replacing deployed resources instead of editing them'],
  ],
  'machine-learning': [
    ['Supervised learning', 'Learning patterns from examples that include target answers'],
    ['Unsupervised learning', 'Finding structure in data without target answers'],
    ['Classification', 'Predicting one category from a set of categories'],
    ['Regression', 'Predicting a continuous numeric value'],
    ['Feature', 'An input variable used by a model'],
    ['Label', 'The target answer a supervised model learns to predict'],
    ['Training set', 'The examples used to fit model parameters'],
    ['Test set', 'Separate examples used for final model evaluation'],
    ['Overfitting', 'Learning training details that do not generalize well'],
    ['Underfitting', 'Using a model too simple to learn important patterns'],
    ['Model', 'A learned function that maps inputs to predictions'],
    ['Accuracy', 'The fraction of predictions that are correct'],
    ['Precision', 'The fraction of positive predictions that are truly positive'],
    ['Recall', 'The fraction of actual positives that are found'],
    ['Cross-validation', 'Repeatedly evaluating a model on different data splits'],
  ],
} as const satisfies Record<string, readonly QuizConcept[]>;
